pipelines:
  - name: gcp_poc_pipeline
    configuration:
      environmentVariables:
        readOnly:
          version: "{{gitBranch}}"
          packerVersion: "1.4.5"
          rtRegistry: "pipelines-docker"
    steps:
      - name: build_U16_gcp
        type: Bash
        configuration:
          environmentVariables:
            os: "Ubuntu_16.04"
            arch: "x86_64"
          integrations:
            - name: gcpInt
          inputResources:
            - name: gcpPocGit
        execution:
          onExecute:
            - pushd $res_gcpPocGit_resourcePath
            - popd
            - pushd $res_gcpPocGit_resourcePath
            - echo $int_gcpInt_jsonKey > serviceAccount.json
            - rm -rf /tmp/packer && mkdir -p /tmp/packer
            - PK_FILE="packer_${packerVersion}_linux_amd64.zip"
            - wget -nv https://releases.hashicorp.com/packer/${packerVersion}/$PK_FILE
            - unzip -o $PK_FILE -d /tmp/packer
            - sudo chmod +x /tmp/packer/packer
            - mv /tmp/packer/packer /usr/bin/packer
            - curl https://sdk.cloud.google.com > install.sh
            - bash install.sh --disable-prompts
            - exec -l $SHELL
            - ./buildImages.sh
            - popd
